# Generated by Django 3.2.3 on 2021-07-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_click'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='books',
            name='publisher',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=5000),
        ),
    ]
